# This workflow pulls data from Traveller Map and stores it in the repo
name: Map Data Update

# Controls when the workflow will run
on:
  schedule:
  # Run midnight each Monday
  - cron: "0 0 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Download a new copy of the map data from Traveller Map
      - name: Map Data Download
        run: python ./scripts/map_update.py

      # Commit any changes. A check is made that there is more than 1 file changed as the timestamp
      # file is always expected to have changed
      - name: Commit Changes
        run: |
          git config --global user.name 'cthulhustig'
          git config --global user.email 'cthulhustig@users.noreply.github.com'
          git add ./map
          if [ $(git diff --cached --numstat | wc -l) -gt 1 ]; then
            git commit -m "Automated map data update"
            git push
          else
            echo "No changes to commit"
          fi

