# This workflow pulls data from Traveller Map and stores it in the repo
name: Map Data Update

# Controls when the workflow will run
on:
  schedule:
  # TODO: Currently running daily at midnight for testing, should be something less frequent (e.g. "0 0 * * 1" to run midnight on a monday)
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Download a new copy of the map data from Traveller Map
      - name: Map Data Download
        run: python ./scripts/map_update.py

      # Commit any changes
      - name: Commit Changes
        run: |
          git config --global user.name 'cthulhustig'
          git config --global user.email 'cthulhustig@users.noreply.github.com'
          git add ./map
          if [ $(git diff --cached --numstat | wc -l) -gt 0 ]; then
            git commit -m "Automated map data update"
            git push
          else
            echo "No changes to commit"
          fi

